//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perforce.P4VS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SolutionExplorerResourses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SolutionExplorerResourses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perforce.P4Vs.SolutionExplorer.SolutionExplorerResourses", typeof(SolutionExplorerResourses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_00 {
            get {
                object obj = ResourceManager.GetObject("Glyph_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_01 {
            get {
                object obj = ResourceManager.GetObject("Glyph_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_02 {
            get {
                object obj = ResourceManager.GetObject("Glyph_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_03 {
            get {
                object obj = ResourceManager.GetObject("Glyph_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_04 {
            get {
                object obj = ResourceManager.GetObject("Glyph_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_05 {
            get {
                object obj = ResourceManager.GetObject("Glyph_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_06 {
            get {
                object obj = ResourceManager.GetObject("Glyph_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_07 {
            get {
                object obj = ResourceManager.GetObject("Glyph_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_08 {
            get {
                object obj = ResourceManager.GetObject("Glyph_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_09 {
            get {
                object obj = ResourceManager.GetObject("Glyph_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_10 {
            get {
                object obj = ResourceManager.GetObject("Glyph_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_11 {
            get {
                object obj = ResourceManager.GetObject("Glyph_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_12 {
            get {
                object obj = ResourceManager.GetObject("Glyph_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_13 {
            get {
                object obj = ResourceManager.GetObject("Glyph_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_14 {
            get {
                object obj = ResourceManager.GetObject("Glyph_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glyph_15 {
            get {
                object obj = ResourceManager.GetObject("Glyph_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

		internal static System.Drawing.Bitmap Glyph_18
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_18", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_20
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_20", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_21
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_21", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_22
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_22", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_23
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_23", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_28
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_28", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_33
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_33", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_35
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_35", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_37
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_37", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_38
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_38", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}

		internal static System.Drawing.Bitmap Glyph_44
		{
			get
			{
				object obj = ResourceManager.GetObject("Glyph_44", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
